import { act, renderHook, waitFor } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { useDesktop } from '../useDesktop';
import type { Bridge } from '../types';
it('does not start overlapping scans while an IPC start is pending',async()=>{
 let finish!:(ticket:number)=>void;
 const start=vi.fn(()=>new Promise<number>(resolve=>{finish=resolve;}));
 const bridge={settings:async()=>({workspaces:[],config_path:'fixture',include_personal:false}),start,status:async()=>({running:null,completed:0,generation:0,progress:null,invalidated:false,error:null,watch_errors:[]})} as unknown as Bridge;
 const {result,unmount}=renderHook(()=>useDesktop(bridge));
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(1));
 await new Promise(resolve=>setTimeout(resolve,450));
 await act(async()=>{await result.current.refresh();});
 expect(start).toHaveBeenCalledTimes(1);
 await act(async()=>{finish(1);});unmount();
});
it('queues registration refresh behind a focus scan even when its old inventory is rejected',async()=>{
 const empty={generation:0,status:'complete',repositories:{checkouts:[],issues:[],roots:[],worktree_candidates:[]},sources:[],artifacts:[],packages:[],contexts:[],diagnostics:[],linked_sources:[]};
 let serial=0,registered=false;
 let state={running:null as number|null,completed:0,generation:0,progress:null,invalidated:false,error:null,watch_errors:[]};
 const start=vi.fn(async()=>{serial++;state={...state,running:serial};return serial;});
 const bridge={settings:async()=>({workspaces:[],config_path:'fixture',include_personal:false}),start,status:async()=>({...state}),inventory:async(g:number)=>{if(g===2&&registered)throw new Error('Workspace settings changed');return {...empty,generation:g};},chooseWorkspace:async()=>{registered=true;return {workspaces:[],config_path:'fixture',include_personal:false};}} as unknown as Bridge;
 const {result,unmount}=renderHook(()=>useDesktop(bridge));
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(1));
 state={...state,running:null,completed:1,generation:1};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(1));
 await act(async()=>{await result.current.refresh();}); // focus refresh enters the same function
 expect(start).toHaveBeenCalledTimes(2);
 await act(async()=>{await result.current.add('New root');});
 expect(start).toHaveBeenCalledTimes(2);
 state={...state,running:null,completed:2,generation:2};
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(3));
 state={...state,running:null,completed:3,generation:3};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(3));
 expect(result.current.error).toBeNull();unmount();
});
it('clears removed selections and queues a fresh inventory behind an active scan',async()=>{
 let settings={workspaces:[{id:'w',name:'Work',roots:[{id:'r',path:'/fixture'}]}],config_path:'fixture',include_personal:false};
 const empty={provider:'codex',generation:0,status:'complete',repositories:{checkouts:[],issues:[],roots:[],worktree_candidates:[]},sources:[],artifacts:[],packages:[],contexts:[],diagnostics:[],linked_sources:[]};
 let serial=0;
 let state={running:null as number|null,completed:0,generation:0,progress:null,invalidated:false,error:null,watch_errors:[]};
 const start=vi.fn(async()=>{serial++;state={...state,running:serial};return serial;});
 const removeLocation=vi.fn(async()=>{settings={...settings,workspaces:[]};return settings;});
 const bridge={settings:async()=>settings,start,status:async()=>({...state}),inventory:async(g:number)=>({...empty,generation:g}),removeLocation} as unknown as Bridge;
 const {result,unmount}=renderHook(()=>useDesktop(bridge));
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(1));
 state={...state,running:null,completed:1,generation:1};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(1));
 await act(async()=>{await result.current.refresh({workspace_id:'w'});});
 await act(async()=>{await result.current.remove('r');});
 expect(removeLocation).toHaveBeenCalledWith('r');
 expect(result.current.settings?.workspaces).toEqual([]);
 expect(result.current.selection.workspace_id).toBeNull();
 expect(result.current.inventory).toBeNull();
 expect(start).toHaveBeenCalledTimes(2);
 state={...state,running:null,completed:2,generation:2};
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(3));
 expect(start).toHaveBeenLastCalledWith(expect.objectContaining({workspace_id:null}));
 state={...state,running:null,completed:3,generation:3};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(3));
 expect(result.current.error).toBeNull();unmount();
});
it('does not restore stale settings when an inventory read finishes after removal',async()=>{
 let settings={workspaces:[{id:'w',name:'Work',roots:[{id:'r',path:'/remove'},{id:'keep',path:'/keep'}]}],config_path:'fixture',include_personal:false};
 const empty={provider:'codex',generation:0,status:'complete',repositories:{checkouts:[],issues:[],roots:[],worktree_candidates:[]},sources:[],artifacts:[],packages:[],contexts:[],diagnostics:[],linked_sources:[]};
 let serial=0;
 let state={running:null as number|null,completed:0,generation:0,progress:null,invalidated:false,error:null,watch_errors:[]};
 let finishOld!:(value:unknown)=>void;
 const start=vi.fn(async()=>{serial++;state={...state,running:serial};return serial;});
 const inventory=vi.fn(async(g:number)=>g===2?new Promise(resolve=>{finishOld=resolve;}):({...empty,generation:g}));
 const bridge={settings:async()=>settings,start,status:async()=>({...state}),inventory,removeLocation:async()=>{settings={...settings,workspaces:[{...settings.workspaces[0],roots:[{id:'keep',path:'/keep'}]}]};return settings;}} as unknown as Bridge;
 const {result,unmount}=renderHook(()=>useDesktop(bridge));
 await waitFor(()=>expect(start).toHaveBeenCalledTimes(1));
 state={...state,running:null,completed:1,generation:1};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(1));
 await act(async()=>{await result.current.refresh({workspace_id:'w'});});
 state={...state,running:null,completed:2,generation:2};
 await waitFor(()=>expect(inventory).toHaveBeenCalledWith(2));
 await act(async()=>{await result.current.remove('r');});
 await act(async()=>{finishOld({...empty,generation:2});});
 expect(result.current.inventory).toBeNull();
 expect(result.current.settings?.workspaces[0].roots.map(root=>root.id)).toEqual(['keep']);
 expect(start).toHaveBeenLastCalledWith(expect.objectContaining({workspace_id:'w'}));
 state={...state,running:null,completed:3,generation:3};
 await waitFor(()=>expect(result.current.inventory?.generation).toBe(3));
 unmount();
});
